### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by PTcampbell** [DigitalWheat/Shopify#1]
Hi – thanks for this. I've managed to set up everything but how do you use the Product resource controller? For example, simply getting products on the dashboard page. I'm having trouble making the app and actually using the product resource. Thanks!

**Comment by maxkostinevich** [comment]
Hello, you can use [Service Container](https://laravel.com/docs/5.4/container) to use resource controller, for example, your ProductsController may look as follows (please, do not forget to register appropriate routes and views): 
````
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DigitalWheat\Shopify\ShopifyResourceFactory;

class ProductsController extends Controller
{

    protected $resourceFactory;

    public function __construct(ShopifyResourceFactory $resourceFactory)
    {
        $this->resourceFactory = $resourceFactory;
        $this->middleware(['shopify.login']);
    }

    public function index()
    {
        $products = $this->getProducts();
        return view('shopify::app.products', [
            'user' => auth()->user(),
            'products' => $products
        ]);
    }

    protected function getProducts()
    {
        return $this->resourceFactory->setUser(auth()->user())->resource('Product')->all();
    }
}
````

Hope it helps!
